# Generated by Django 5.2.3 on 2025-06-20 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trustpay_trx', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='trx_reference',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
