# Generated by Django 5.2.3 on 2025-06-20 23:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trustpay_trx', '0003_alter_transaction_trx_reference'),
    ]

    operations = [
        migrations.AddField(
            model_name='cryptodeposit',
            name='transaction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='crypto_deposit', to='trustpay_trx.transaction'),
        ),
        migrations.AddField(
            model_name='transfer',
            name='transaction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfer_trx', to='trustpay_trx.transaction'),
        ),
        migrations.AddField(
            model_name='withdrawal',
            name='transaction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trx_withdraw', to='trustpay_trx.transaction'),
        ),
    ]
