# Generated by Django 5.2.3 on 2025-06-20 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trustpay_trx', '0004_cryptodeposit_transaction_transfer_transaction_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cryptodeposit',
            name='trx_reference',
            field=models.CharField(blank=True, editable=False, max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='transfer',
            name='trx_reference',
            field=models.CharField(blank=True, editable=False, max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='withdrawal',
            name='trx_reference',
            field=models.CharField(blank=True, editable=False, max_length=100, null=True, unique=True),
        ),
    ]
