# Generated by Django 5.2.3 on 2025-06-21 17:03

import django.db.models.deletion
import trustpay_trx.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trustpay_trx', '0006_alter_cryptodeposit_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chequedeposit',
            name='is_confirmed',
        ),
        migrations.RemoveField(
            model_name='chequedeposit',
            name='trx_reference',
        ),
        migrations.RemoveField(
            model_name='cryptodeposit',
            name='is_confirmed',
        ),
        migrations.RemoveField(
            model_name='cryptodeposit',
            name='trx_reference',
        ),
        migrations.RemoveField(
            model_name='withdrawal',
            name='transaction_status',
        ),
        migrations.RemoveField(
            model_name='withdrawal',
            name='trx_reference',
        ),
        migrations.AddField(
            model_name='chequedeposit',
            name='trx_status',
            field=models.ForeignKey(blank=True, default=trustpay_trx.models.get_pending_status, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cheque_trx_status', to='trustpay_trx.transactionstatus'),
        ),
        migrations.AddField(
            model_name='cryptodeposit',
            name='trx_status',
            field=models.ForeignKey(blank=True, default=trustpay_trx.models.get_pending_status, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='crypo_trx_status', to='trustpay_trx.transactionstatus'),
        ),
        migrations.AddField(
            model_name='withdrawal',
            name='trx_status',
            field=models.ForeignKey(blank=True, default=trustpay_trx.models.get_pending_status, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='withdraw_trx_status', to='trustpay_trx.transactionstatus'),
        ),
        migrations.AlterField(
            model_name='chequedeposit',
            name='transaction',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cheque_trx', to='trustpay_trx.transaction'),
        ),
        migrations.AlterField(
            model_name='cryptodeposit',
            name='transaction',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='crypto_trx', to='trustpay_trx.transaction'),
        ),
        migrations.AlterField(
            model_name='withdrawal',
            name='transaction',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='withdraw_trx', to='trustpay_trx.transaction'),
        ),
        migrations.AlterField(
            model_name='withdrawal',
            name='transaction_method',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='withdraw_method', to='trustpay_trx.transactionmethod'),
        ),
    ]
