# Generated by Django 5.2.3 on 2025-06-22 14:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trustpay_trx', '0007_remove_chequedeposit_is_confirmed_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransferType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transfer_type', models.CharField(max_length=30, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Transfer Type',
                'db_table': 'Transfer Type',
            },
        ),
        migrations.CreateModel(
            name='TransactionCharges',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('charges', models.CharField(max_length=10)),
                ('trf_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='trf_type', to='trustpay_trx.transfertype')),
            ],
            options={
                'verbose_name_plural': 'Transaction Charges',
                'db_table': 'Transaction Charges',
            },
        ),
    ]
