# Generated by Django 5.2.3 on 2025-06-24 07:54

import django.db.models.deletion
import trustpay_trx.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trustpay_trx', '0008_transfertype_transactioncharges'),
        ('trustpay_user', '0006_transactionpin'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ACHTransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient_name', models.CharField(blank=True, max_length=100, null=True)),
                ('recipient_account', models.CharField(blank=True, max_length=20, null=True)),
                ('routing_number', models.CharField(blank=True, max_length=11, null=True)),
                ('trx_reference', models.CharField(blank=True, editable=False, max_length=100, null=True, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('account_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trx_acct', to='trustpay_user.accounttype')),
                ('transaction', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfer_trx', to='trustpay_trx.transaction')),
                ('trx_status', models.ForeignKey(blank=True, default=trustpay_trx.models.get_pending_status, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ach_trx_status', to='trustpay_trx.transactionstatus')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sender', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'ACH Transfers',
                'db_table': 'ACH Transfer',
            },
        ),
        migrations.DeleteModel(
            name='Transfer',
        ),
    ]
