# Generated by Django 5.2.3 on 2025-06-24 13:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trustpay_trx', '0009_achtransfer_delete_transfer'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='achtransfer',
            old_name='recipient_name',
            new_name='account_name',
        ),
        migrations.AlterField(
            model_name='achtransfer',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ach_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='IMFCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, default='IMFDUS3WNO2', max_length=20, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_imf', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'IMFCode',
                'db_table': 'IMFCode',
            },
        ),
    ]
