# Generated by Django 5.2.3 on 2025-06-24 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trustpay_trx', '0010_rename_recipient_name_achtransfer_account_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='achtransfer',
            old_name='recipient_account',
            new_name='account_number',
        ),
    ]
