# Generated by Django 5.2.3 on 2025-06-24 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trustpay_trx', '0012_domesticwire'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllBank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_name', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'verbose_name_plural': 'All Bank',
                'db_table': 'All Bank',
            },
        ),
    ]
