# Generated by Django 5.2.3 on 2025-06-25 10:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trustpay_trx', '0013_allbank'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='domesticwire',
            name='account_type',
        ),
        migrations.AddField(
            model_name='domesticwire',
            name='bank_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='d_wire_banks', to='trustpay_trx.allbank'),
        ),
    ]
