# Generated by Django 5.2.3 on 2025-06-25 15:17

import django.db.models.deletion
import trustpay_trx.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trustpay_trx', '0014_remove_domesticwire_account_type_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InternationalWire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_name', models.CharField(blank=True, max_length=100, null=True)),
                ('account_number', models.CharField(blank=True, max_length=20, null=True)),
                ('bank_address', models.CharField(blank=True, max_length=255, null=True)),
                ('swift_bic_code', models.CharField(blank=True, max_length=11, null=True)),
                ('iban', models.CharField(blank=True, max_length=34, null=True)),
                ('country', models.CharField(blank=True, max_length=100, null=True)),
                ('trx_reference', models.CharField(blank=True, editable=False, max_length=100, null=True, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('bank_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='f_wire_banks', to='trustpay_trx.allbank')),
                ('transaction', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='f_wire_trx', to='trustpay_trx.transaction')),
                ('trx_status', models.ForeignKey(blank=True, default=trustpay_trx.models.get_pending_status, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='f_wire_trx_status', to='trustpay_trx.transactionstatus')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='f_wire_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'International Wire',
                'db_table': 'International Wire',
            },
        ),
    ]
