# Generated by Django 5.2.3 on 2025-06-25 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trustpay_trx', '0015_internationalwire'),
    ]

    operations = [
        migrations.AlterField(
            model_name='internationalwire',
            name='bank_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
