# Generated by Django 5.2.3 on 2025-06-25 16:41

import django.db.models.deletion
import trustpay_trx.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trustpay_trx', '0016_alter_internationalwire_bank_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='trx_status',
            field=models.ForeignKey(blank=True, default=trustpay_trx.models.get_pending_status, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trx_status', to='trustpay_trx.transactionstatus'),
        ),
    ]
