# Generated by Django 5.2.3 on 2025-06-26 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trustpay_trx', '0017_transaction_trx_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoanType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loan_type', models.CharField(max_length=20, unique=True)),
            ],
            options={
                'verbose_name_plural': 'LoanType',
                'db_table': 'LoanType',
            },
        ),
    ]
