# Generated by Django 5.2.3 on 2025-06-28 16:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trustpay_trx', '0018_loantype'),
        ('trustpay_user', '0007_accountmanagerinfo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MortgageApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_requested', models.DecimalField(decimal_places=2, max_digits=12)),
                ('annual_income', models.DecimalField(decimal_places=2, max_digits=12)),
                ('credit_score', models.IntegerField()),
                ('credit_report', models.FileField(upload_to='credit_reports/')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('employment_status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mortgage_emp_status', to='trustpay_user.employmentstatus')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mortgage_status', to='trustpay_trx.transactionstatus')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mortgage_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Mortgage Application',
                'db_table': 'Mortgage Application',
            },
        ),
        migrations.CreateModel(
            name='EmploymentAndPropertyAppraisal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employer_name', models.CharField(max_length=100)),
                ('hr_contact', models.CharField(max_length=100)),
                ('proof_of_income', models.FileField(upload_to='income_proofs/')),
                ('property_value', models.DecimalField(decimal_places=2, max_digits=12)),
                ('appraisal_report', models.FileField(upload_to='appraisals/')),
                ('sales_contract', models.FileField(blank=True, null=True, upload_to='property_contracts/')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='mortgage_application', to='trustpay_trx.mortgageapplication')),
            ],
            options={
                'verbose_name_plural': 'Employment And Property Appraisal',
                'db_table': 'Employment And Property Appraisal',
            },
        ),
    ]
