# Generated by Django 5.2.3 on 2025-06-28 16:45

import django.db.models.deletion
import trustpay_trx.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trustpay_trx', '0019_mortgageapplication_employmentandpropertyappraisal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mortgageapplication',
            name='status',
            field=models.ForeignKey(default=trustpay_trx.models.get_pending_status, on_delete=django.db.models.deletion.CASCADE, related_name='mortgage_status', to='trustpay_trx.transactionstatus'),
        ),
    ]
