# Generated by Django 5.2.3 on 2025-06-28 20:44

import django.db.models.deletion
import trustpay_trx.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trustpay_trx', '0020_alter_mortgageapplication_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='MortgageDeposit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deposit_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('approved', models.BooleanField(default=False)),
                ('cheque_front_img', models.ImageField(blank=True, null=True, upload_to='uploads/cheque/')),
                ('cheque_back_img', models.ImageField(blank=True, null=True, upload_to='uploads/cheque/')),
                ('trx_reference', models.CharField(blank=True, default=trustpay_trx.models.generate_transaction_reference, max_length=100, null=True, unique=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='mortgage_deposit', to='trustpay_trx.mortgageapplication')),
            ],
            options={
                'verbose_name_plural': 'Mortgage Deposit',
                'db_table': 'Mortgage Deposit',
            },
        ),
    ]
