# Generated by Django 5.2.3 on 2025-06-18 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trustpay_auth', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='emailsendcount',
            options={'verbose_name_plural': 'Email Send Count'},
        ),
    ]
