# Generated by Django 5.2.3 on 2025-06-18 20:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trustpay_user', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_type', models.CharField(max_length=20, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Account Type',
                'db_table': 'Account Type',
            },
        ),
        migrations.CreateModel(
            name='EmploymentStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_title', models.CharField(max_length=20, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Employment Status',
                'db_table': 'Employment Status',
            },
        ),
        migrations.CreateModel(
            name='BankAccountInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issued_id', models.ImageField(blank=True, null=True, upload_to='uploads/issued_id/')),
                ('account_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='acct_type', to='trustpay_user.accounttype')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bank_info', to=settings.AUTH_USER_MODEL)),
                ('employment_status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='emp_status', to='trustpay_user.employmentstatus')),
            ],
        ),
    ]
