# Generated by Django 5.2.3 on 2025-06-19 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trustpay_user', '0002_accounttype_employmentstatus_bankaccountinfo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bankaccountinfo',
            options={'verbose_name_plural': 'BankAccount Info'},
        ),
        migrations.AlterField(
            model_name='contactinfo',
            name='city',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='contactinfo',
            name='country',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='contactinfo',
            name='state',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='contactinfo',
            name='zip_code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='personalinfo',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='personalinfo',
            name='first_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='personalinfo',
            name='last_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='personalinfo',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True, unique=True),
        ),
        migrations.AlterModelTable(
            name='bankaccountinfo',
            table='BankAccount Info',
        ),
    ]
