# Generated by Django 5.2.3 on 2025-06-19 16:52

import phonenumber_field.modelfields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trustpay_user', '0003_alter_bankaccountinfo_options_alter_contactinfo_city_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personalinfo',
            name='phone_number',
        ),
        migrations.AlterField(
            model_name='contactinfo',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, db_index=True, max_length=128, null=True, region=None, unique=True),
        ),
    ]
