# Generated by Django 5.2.3 on 2025-06-19 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trustpay_user', '0004_remove_personalinfo_phone_number_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bankaccountinfo',
            options={'verbose_name_plural': 'Bank Account Info'},
        ),
        migrations.AlterModelTable(
            name='bankaccountinfo',
            table='Bank Account Info',
        ),
    ]
