# Generated by Django 5.2.3 on 2025-06-26 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trustpay_user', '0006_transactionpin'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountManagerInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=50, null=True)),
                ('last_name', models.CharField(blank=True, max_length=50, null=True)),
                ('phone', models.CharField(blank=True, max_length=50, null=True)),
                ('email', models.CharField(blank=True, db_index=True, max_length=100, null=True, unique=True, verbose_name='email address')),
                ('pic', models.ImageField(blank=True, default='img/user.png', null=True, upload_to='uploads/profile/')),
            ],
            options={
                'verbose_name_plural': 'Account Manager Info',
                'db_table': 'Account Manager Info',
            },
        ),
    ]
